Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Controllers/BindingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Asp.Net.Mvc.Check.Models;

namespace Asp.Net.Mvc.Check.Controllers
{
    public class BindingController : Controller
    {
        private readonly PersonModel[] _personData;

        public BindingController()
        {
            _personData = new[]
            {
                new PersonModel
                {
                    PersonId = 1,
                    FirstName = "Adam",
                    LastName = "Freeman",
                    Role = Role.Admin
                },
                new PersonModel
                {
                    PersonId = 2,
                    FirstName = "Jacqui",
                    LastName = "Griffyth",
                    Role = Role.User
                },
                new PersonModel
                {
                    PersonId = 3,
                    FirstName = "John",
                    LastName = "Smith",
                    Role = Role.User
                },
                new PersonModel
                {
                    PersonId = 4,
                    FirstName = "Anne",
                    LastName = "Jones",
                    Role = Role.Guest
                }
            };
        }

        public ActionResult Index(int? id = 1)
        {
            var a = TempData["test"];
            var dataItem = _personData.First(p => p.PersonId == id);

            return View(dataItem);
        }

        public ActionResult CreatePerson()
        {
            var newCultureName = "fr-FR";
            var cookie = new HttpCookie("_culture", newCultureName);
            cookie.Expires = DateTime.Today.AddYears(1);
            Response.SetCookie(cookie);

            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(newCultureName);

            return View(new PersonModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePerson(PersonModel model)
        {
            return View("Index", model);
        }

        public ActionResult DisplaySummary([Bind(Prefix = "HomeAddress", Exclude = "Country")] AddressSummaryModel summary)
        {
            return View(summary);
        }

        public ActionResult Names(string[] names)
        {
            names = names ?? new string[0];

            return View(names);
        }

        public ActionResult Address(FormCollection formData)
        {
            var addresses = new List<AddressSummaryModel>();
            UpdateModel(addresses, formData);

            //if (TryUpdateModel(addresses, formData))
            //{
            //    // proceed as normal
            //}
            //else
            //{
            //    // provide feedback to user
            //}

            return View(addresses);
        }

        public ActionResult Address(IList<AddressSummaryModel> addresses)
        {

            addresses = addresses ?? new List<AddressSummaryModel>();

            return View(addresses);
        }
    }
}

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Binding/Address.cshtml
@using Asp.Net.Mvc.Check.Models;
@model IList<AddressSummaryModel>

@{
    ViewBag.Title = "Address";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Addresses</h2>
@if (Model.Count() == 0)
{
    using (Html.BeginForm())
    {
        for (var i = 0; i < 3; i++)
        {
            <fieldset>
                <legend>Address @(i + 1)</legend>
                <div>
                    <label>City:</label>
                    @Html.Editor("[" + i + "].City")
                </div>
                <div>
                    <label>Country:</label>
                    @Html.Editor("[" + i + "].Country")
                </div>
            </fieldset>
        }
        <button type="submit">Submit</button>
    }
}
else
{
    foreach (AddressSummaryModel str in Model)
    {
        <p>@str.City, @str.Country</p>
    }
    @Html.ActionLink("Back", "Address");
}

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Binding/CreatePerson.cshtml
@model Asp.Net.Mvc.Check.Models.PersonModel

@{
    ViewBag.Title = "CreatePerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create Person</h2>

@*@using (Html.BeginForm())*@

@using (Html.BeginForm("DisplaySummary", "Binding"))
{
    @Html.AntiForgeryToken()
    <div>
        @Html.LabelFor(m => m.PersonId)
        @Html.EditorFor(m => m.PersonId)
    </div>
    <div>
        @Html.LabelFor(m => m.FirstName)
        @Html.EditorFor(m => m.FirstName)
    </div>
    <div>
        @Html.LabelFor(m => m.LastName)
        @Html.EditorFor(m => m.LastName)
    </div>
    <div>
        @Html.LabelFor(m => m.Role)
        @Html.EditorFor(m => m.Role)
    </div>
    <div>
        @Html.LabelFor(m => m.HomeAddress.City)
        @Html.EditorFor(m => m.HomeAddress.City)
    </div>
    <div>
        @Html.LabelFor(m => m.HomeAddress.Country)
        @Html.EditorFor(m => m.HomeAddress.Country)
    </div>
    <button type="submit">Submit</button>
}

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Binding/DisplaySummary.cshtml
@model Asp.Net.Mvc.Check.Models.AddressSummaryModel

@{
    ViewBag.Title = "DisplaySummary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Address Summary</h2>

<div><label>City:</label>@Html.DisplayFor(m => m.City)</div>
<div><label>Country:</label>@Html.DisplayFor(m => m.Country)</div>

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Binding/Index.cshtml
@model Asp.Net.Mvc.Check.Models.PersonModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Person</h2>

<div>
    <label>ID:</label>
    @Html.DisplayFor(m => m.PersonId)
</div>
<div>
    <label>First Name:</label>
    @Html.DisplayFor(m => m.FirstName)
</div>
<div>
    <label>Last Name:</label>
    @Html.DisplayFor(m => m.LastName)
</div>
<div>
    <label>Role:</label>
    @Html.DisplayFor(m => m.Role)
</div>
<div>
    <label>City:</label>
    @Html.DisplayFor(m => m.HomeAddress.City)
</div>
<div>
    <label>Country:</label>
    @Html.DisplayFor(m => m.HomeAddress.Country)
</div>

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Binding/Names.cshtml
@model string[]

@{
    ViewBag.Title = "Names";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Names</h2>

@if (Model.Length == 0)
{
    using (Html.BeginForm())
    {
        for (var i = 0; i < 3; i++)
        {
            <div><label>@(i + 1):</label>@Html.TextBox("names")</div>
        }
        <button type="submit">Submit</button>
    }
}
else
{
    foreach (string str in Model)
    {
        <p>@str</p>
    }
    @Html.ActionLink("Back", "Names");
}