Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Controllers/NewController.cs
using System.Web.Mvc;
using Asp.Net.Mvc.Check.Models;

namespace Asp.Net.Mvc.Check.Controllers
{
    [RoutePrefix("Users")]
    public class NewController : Controller
    {
        public ActionResult Index()
        {
            var b = TempData["test"];


            return RedirectToAction("Test");
        }

        [Route("NewAbout")]
        public ActionResult About()
        {
            var a = TempData["login"];
                
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [Route("~/TestL")]
        public ActionResult Test(TestEnum b = default)
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Shared/Boolean.cshtml
@model bool?

@if (ViewData.ModelMetadata.IsNullableValueType)
{
    @Html.DropDownListFor(m => m, new SelectList(new[] { "Not Set", "True", "False" }, Model))
}
else
{
    var state = ViewData.ModelState[ViewData.ModelMetadata.PropertyName];
    var value = Model ?? false;
    if (state != null && state.Errors.Count > 0)
    {
        <span class="input-validation-error" style="padding: 0; margin: 1px">
            @Html.CheckBox("", value)
        </span>
    }
    else
    {
        @Html.CheckBox("", value)
    }
}

Asp.Net.Mvc.Check/Asp.Net.Mvc.Check/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        .field-validation-error {
            color: #f00;
        }

        .validation-summary-errors {
            color: #f00;
            font-weight: bold;
        }

        .input-validation-error {
            border: 2px solid #f00;
            background-color: #fee;
        }

        input[type="checkbox"].input-validation-error {
            outline: 2px solid #f00;
        }

        label {
            display: inline-block;
            width: 100px;
        }

        div.dataElem {
            margin: 5px;
        }
    </style>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "New")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderSection("Header", false)
        <div class="layout">
            This is part of the layout
        </div>
        @RenderBody()
        <div class="layout">
            This is part of the layout
        </div>
        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer")
        }
        else
        {
            <h4>This is the default footer</h4>
        }
        <div class="layout">
            This is part of the layout
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>